<?php
/**
 * Mozg Bradesco Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mozg
 * @package    Mozg_Bradesco
 * @copyright    Copyright (c) 2011 Mozg (http://www.mozg.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Mozg_Bradesco
 * @author     Mozg
 * @property   Mozg B.V
 * @copyright  Copyright (c) 2014 Mozg BV (http://www.mozg.com)
 */
?>
<?php
/** @var Mozg_Bradesco_Block_Form_Ideal $this */
?>
<?php $_code = $this->getMethodCode() ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <label for="payment[mozg_bradesco_shopfacil_ideal_type]">
            <?php echo $this->__('Choose Your Bank') ?>
        </label>
    </li>
    <?php

    $size = count($this->getIssuers());
    $count = 1;

    foreach ($this->getIssuers() as $_issuerId => $_issuerData): ?>
        <li>
            <label class="mozg-bradesco-api-ideal-image-label" for="mozg_bradesco_shopfacil_ideal_type_<?php echo $_issuerId ?>">
                <input type="radio" id="mozg_bradesco_shopfacil_ideal_type_<?php echo $_issuerId ?>"
                       name="payment[mozg_issuer_type]" value="<?php echo $_issuerId ?>"
                       class="<?php if ($size == $count) {
                           echo 'validate-one-required-by-name';
                       } ?>"
                       <?php if (isset($_issuerData['selected'])): ?>checked<?php endif; ?>

                />
                <img src="<?php echo $this->getIssuerImageUrl($_issuerData); ?>"
                     alt="<?php echo $_issuerData['label'] ?>"/>
            </label>
        </li>
        <?php
        $count++;
    endforeach; ?>
</ul>
