<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php //TODO add a form to add data here, currently only on Mozg. ?>
<?php
/** @var Mozg_Bradesco_Block_Form_Openinvoice $this */
$_code = $this->getMethodCode();
?>
<fieldset class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
    <ul>

        <?php if($this->genderShow()):?>
        <li class="fields">
            <label for="gender" class="required"><?php echo $this->__('Gender') ?> <em class="required">*</em></label>
            <div class="input-box">
                <select id="gender" name="payment[gender]" title="<?php echo $this->__('Gender') ?>" class="validate-select">
                    <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();?>
                    <?php $value = $this->getGender();?>
                    <?php foreach ($options as $option):?>
                        <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $this->__($option['label']) ?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </li>
        <?php endif; ?>

        <?php if($this->dobShow()):?>
        <li class="fields">
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob')->setTemplate('mozg_bradesco/widget/dob.phtml') ?>

            <?php echo $_dob->setDate($this->getDate())->setFieldIdFormat($_code.':%s')->setFieldNameFormat('payment[%s]')->toHtml() ?>
        </li>
        <?php endif; ?>
        <?php if($this->telephoneShow()):?>
        <li class="fields">
                <label for="billing:telephone" class="required"><?php echo $this->__('Telephone') ?> <em class="required">*</em></label>
                <div class="input-box">
                    <input type="tel" name="payment[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                </div>
        </li>
        <?php endif; ?>

        <li class="fields">
            <?php echo $this->__('You will be redirected to Mozg website when you place an order.') ?>
        </li>
    </ul>
    <?php if(!$this->isRatePay()):?>
    <input type="hidden" name="payment[dfvalue]" id="dfValue"/>
    <script type="text/javascript">
        //<![CDATA[
        var dfDoInit = function() {
                dfSet('dfValue', 0);
            }
        dfDoInit();
        //]]>
    </script>
    <?php else: ?>
    <input type="hidden" name="payment[dfvalue]" id="dfValue" value="<?php echo $this->calculateDeviceIdentToken()?>"/>
    <script type="text/javascript">
        //<![CDATA[
        var ratePayId = "<?php echo $this->getRatePayId()?>";
        di = {t: '', v: ratePayId, l: 'Checkout'};
        function waitForDfValue() {
            var dfValue = document.getElementById('dfValue');
            if (dfValue && dfValue.value) {
                di.t = dfValue.value.replace(':', '');
                var scriptTag = document.createElement('script');
                scriptTag.src = "//d.ratepay.com/" + ratePayId + "/di.js";
                scriptTag.type = "text/javascript";
                document.body.appendChild(scriptTag);
            } else {
                setTimeout(waitForDfValue, 200);
                }
            }
        waitForDfValue();
        //]]>
    </script>
    <?php endif; ?>
</fieldset>