<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php $_code = $this->getMethodCode() ?>

<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to Mozg app when you place an order.') ?> 
        </li>
        <?php if($this->showRememberThisCheckoutbox()): ?>
            <li id="mozg-remember-these-details" class="mozg_bradesco_input_fields">
                <div class="input-box">
                    <div class="v-fix">
                        <input type="checkbox" name="payment[store_cc]" id="<?php echo $_code ?>_store_cc" value="1" checked />
                        <label for="<?php echo $_code ?>_store_cc" class="required"><em>*</em><?php echo $this->__('Remember these details') ?></label>
                    </div>
                </div>
            </li>
            <script type="text/javascript">
                // don't show save cc for quest checkout. Only possible to detect with javascript
                if ($('login:guest') && $('login:guest').checked) {
                    $('mozg-remember-these-details').hide();
                }
            </script>
        <?php endif; ?>
    </ul>
</fieldset>