<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
$_code = $this->getMethodCode();
/** @var $this Mozg_Bradesco_Block_Form_Sepa */
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li class="no-agreement">
            <div class="input-box">
                <label for="<?php echo $_code ?>_account_number"><?php echo $this->__('Bank account holder name') ?> <span class="required">*</span></label><br />
                <input
                	type="text" id="<?php echo $_code ?>_account_name" name="payment[account_name]"
                	title="<?php echo $this->__('Bank account holder name') ?>"
                	class="validate-ipayment-sepa-account-name required-entry input-text"
                	value="<?php echo $this->getBankHolderValue(); ?>" autocomplete="off"
                />
            </div>
        </li>
        <li class="no-agreement">
            <div class="input-box">
                <label for="<?php echo $_code ?>_iban"><?php echo $this->__('IBAN') ?> <span class="required">*</span></label><br />
                <input
	                type="text" id="<?php echo $_code ?>_iban" name="payment[iban]"
	                title="<?php echo $this->__('IBAN') ?>"
	                class="validate-ipayment-sepa-iban validate-iban-number required-entry input-text"
	                value="<?php echo $this->getIbanValue(); ?>" autocomplete="off"
                />
            </div>
        </li>

        <li class="no-agreement">
            <div class="input-box">
                <label for="<?php echo $_code ?>_country"><?php echo $this->__('Country') ?> <span class="required">*</span></label><br />
                <select id="<?php echo $_code ?>_country" name="payment[country]" name="payment[country]" title="<?php echo $this->__('Country') ?>" class="validate-ipayment-sepa-country required-entry input-√√√">
                    <option value="">--</option>
                    <?php foreach($this->getCountries() as $_country): ?>
                        <option value="<?php echo $_country['value'] ?>"<?php echo ($_country['value'] == $this->getCountryValue()) ? " selected" : ""; ?>><?php echo $_country['label'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </li>

        <li id="no-agreement">
            <div class="input-box">
                <div class="v-fix">
                    <input class="required-entry" value="1" type="checkbox" name="payment[accept_sepa]" id="<?php echo $_code ?>_accept_sepa" />
                    <label for="<?php echo $_code ?>_accept_sepa"><?php echo $this->__('I agree that the above amount will be debited from my bank account.') ?></label>
                </div>
            </div>
        </li>
    </ul>
</fieldset>
<div>
<span id="ipayment-sepa-please-wait" style="display:none;" class="opc-please-wait">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/> &nbsp; <?php echo $this->__('Submitting payment information...') ?> &nbsp;
</span>
</div>
