<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br/>
<?php if(!$this->inCheckout()):?>
    <a target="_blank" href="<?php echo $this->getMethod()->getInfoInstance()->getAdditionalInformation('payment_url'); ?>"><?php echo $this->__("Click here to pay for your purchase"); ?></a>
<?php endif; ?>