<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php if ($_info = $this->getInfo()): ?>
<?php $sepa = unserialize($this->getInfo()->getPoNumber())?>
<?php echo Mage::helper('mozg_bradesco')->__('Bank account holder name: %s', $this->htmlEscape($sepa['account_name'])) ?><br/>
<?php echo Mage::helper('mozg_bradesco')->__('IBAN: %s', $this->htmlEscape($sepa['iban'])) ?><br/>
<?php echo Mage::helper('mozg_bradesco')->__('Country: %s', $this->htmlEscape($sepa['country'])) ?><br/>
<?php endif; ?>