<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */

/*dump($this->getData());
dump(get_class_methods(get_class($this)));
dump(get_class_vars(get_class($this)));*/

?>

<!-- <?php echo get_class($this) ?> -->

<script type="text/javascript">
console.log('<?php echo get_class($this) ?>');
</script>

<?php if ($this->isCurrentMethod()): ?>

    <div class="bradesco-checkout-onepage-success">

        <?php if ($this->isBoletoPayment() || $this->isEletronicTransferPayment()): ?>
            <div class="payment-url">
                <?php 

                $label_button = Mage::helper('mozg_bradesco')->__('Click here to process transaction');

                echo Mage::helper('mozg_bradesco')->__('<button id="bradesco_transaction" type="submit" class="button" onclick="javascript:openPopupsMozg(\'%s\', \'WinXilinus\', \'Link\', \'Bradesco\', \'bradesco\');"><span><span>%s</span></span></button>', $this->getPaymentUrl(), $label_button);

                ?>

            </div>

            <script type="text/javascript">

            Event.observe (window, "load", function (event){
                console.log('load');
                console.log(event);
                var target= 'target' in event ? event.target : event.srcElement;
                console.log('clicked on '+target.tagName);

                if($('bradesco_transaction')){
                    window.location.href = "#bradesco_transaction";
                    $('bradesco_transaction').click();
                }

            });

            </script>
        <?php endif; ?>

    </div>

<?php endif; ?>

<!-- / <?php echo get_class($this) ?> -->
