<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
$ownerInformation = $this->getInfo()->getCcOwner();
echo $this->htmlEscape($this->getMethod()->getTitle());
?><br/>
<?php if ($_info = $this->getInfo()): ?>
    <?php if ($_info->getMozgPspReference() == ''): ?>
        <?php echo Mage::helper('mozg_bradesco')->__('Payment has not been processed yet.') ?> <br/>
    <?php else :?>
         <?php
    $storeId = $this->getMethod()->getInfoInstance()->getOrder()->getStoreId();
    if($this->getMethod()->getConfigDataDemoMode($storeId)): ?>
            <?php echo Mage::helper('mozg_bradesco')->__('Mozg PSP Reference: <a href="https://ca-test.mozg.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>', $this->htmlEscape($_info->getMozgPspReference()), $this->htmlEscape($_info->getMozgPspReference())) ?> <br/>
        <?php else : ?>
            <?php echo Mage::helper('mozg_bradesco')->__('Mozg PSP Reference: <a href="https://ca-live.mozg.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>', $this->htmlEscape($_info->getMozgPspReference()), $this->htmlEscape($_info->getMozgPspReference())) ?> <br/>
        <?php endif; ?>
    <?php endif;?>

    <?php if($this->getCcTypeName() != ""):?>
        <?php echo Mage::helper('mozg_bradesco')->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?><br/>
    <?php endif; ?>
    <?php if($this->getInfo()->getCcLast4() != ""):?>
        <?php echo Mage::helper('mozg_bradesco')->__('Credit Card Number: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?><br/>
    <?php endif;?>
    <?php endif;?>
    <?php if($this->htmlEscape($this->getInfo()->getMozgAvsResult()) != ""): ?>
        <?php echo Mage::helper('mozg_bradesco')->__('Avs result: %s', $this->htmlEscape($this->getInfo()->getMozgAvsResult())) ?><br/>
    <?php endif; ?>

    <?php if($this->htmlEscape($this->getInfo()->getMozgCvcResult()) != ""): ?>
        <?php echo Mage::helper('mozg_bradesco')->__('Cvc result: %s', $this->htmlEscape($this->getInfo()->getMozgCvcResult())) ?><br/>
    <?php endif; ?>
    <?php if($this->htmlEscape($this->getInfo()->getMozgTotalFraudScore()) != ""): ?>
        <?php echo Mage::helper('mozg_bradesco')->__('Total fraud score: %s', $this->htmlEscape($this->getInfo()->getMozgTotalFraudScore())) ?><br/>
    <?php endif; ?>
    <?php if($this->htmlEscape($this->getInfo()->getAdditionalInformation('number_of_installments')) != "" && $this->htmlEscape($this->getInfo()->getAdditionalInformation('number_of_installments')) > 1): ?>
        <?php echo Mage::helper('mozg_bradesco')->__('Number of installments: %s', $this->htmlEscape($this->getInfo()->getAdditionalInformation('number_of_installments'))) ?><br/>
    <?php endif; ?>
    <?php if($this->htmlEscape($this->getInfo()->getMozgRefusalReasonRaw()) != ""): ?>
        <?php echo Mage::helper('mozg_bradesco')->__('Raw acquirer response: %s', $this->htmlEscape($this->getInfo()->getMozgRefusalReasonRaw())) ?><br/>
    <?php endif; ?>
    <?php if($this->htmlEscape($this->getInfo()->getMozgAuthCode()) != ""): ?>
        <?php echo Mage::helper('mozg_bradesco')->__('Authorisation code: %s', $this->htmlEscape($this->getInfo()->getMozgAuthCode())) ?><br/>
    <?php endif; ?>
    <?php if($this->htmlEscape($this->getInfo()->getMozgAcquirerReference()) != ""): ?>
        <?php echo Mage::helper('mozg_bradesco')->__('Acquirer reference: %s', $this->htmlEscape($this->getInfo()->getMozgAcquirerReference())) ?><br/>
    <?php endif; ?>
